coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%  # coverage can drop by up to 0.5%
    patch: off
comment:
  require_changes: true  # if true: only comment if coverage changes
ignore:
  - "ome_zarr/http_request_handlers.py"   # Tests don't run http server
