#!/usr/bin/env python

import argparse
from ome_zarr import info

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("path")
    args = parser.parse_args()
    info(args.path)
