[tox]
envlist = py{312,313,314}


[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
dependency_groups = tests

commands =
    pytest --cov-report=xml --cov=./ome_zarr  --cov-append {posargs}
