# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__commit_id__",
    "__version__",
    "__version_tuple__",
    "commit_id",
    "version",
    "version_tuple",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Union

    VERSION_TUPLE = tuple[int | str, ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = "0.12.3.dev54+g88fca830c.d20251212"
__version_tuple__ = version_tuple = (0, 12, 3, "dev54", "g88fca830c.d20251212")

__commit_id__ = commit_id = "g88fca830c"
